### ISSUE TITLE
Custom attribute tooltip is overwritten

### ISSUE THREAD

**Issue by MathewHDYT** [ayellowpaper/MinMaxSlider#2]
**Issue:**
When using a `MinMaxSlider` and a `ToolTip` attribute, the text passed to the Tooltip gets overwritten with the currently selected min value the currently selected max value and the range between those two values.

![image](https://user-images.githubusercontent.com/48954742/184214379-7c66bb8a-026d-4703-8554-b3bc2845a32c.png)

**Actual:**
> Min: 1
> Max: 1
> Range: 0

**Expected:**

> Sets the frequency of the sound. Use this to slow down or speed up the sounds.
> Min: 1
> Max: 1
> Range: 0

**Example code:**

```csharp
#if UNITY_EDITOR
        [MinMaxSlider(-3, 3f, SliderFieldPosition.Left, SliderFieldPosition.Right)]
#endif // UNITY_EDITOR
        [Tooltip("Sets the frequency of the sound. Use this to slow down or speed up the sounds.")]
        public Vector2 pitch2 = new Vector2(1f, 1f);
```

**Library code:**

The library seems to check if the actual `content.tooltip` isn't empty and if it isn't append the text instead. From what I could debug tough the `content.tooltip`, is always null even tough there is a `Tooltip` attribute and switching the lines so that the `[Tooltip("")]` is  before or after `[MinMaxSlider()]` didn't matter.

**Comment by MathewHDYT** [comment]
I edited some code and it seems I fixed it.

![image](https://user-images.githubusercontent.com/48954742/184220937-cb97a939-f05f-42de-80ef-7717016b4444.png)

As far as I know the main culprit was not passing the `GUIContent` from the `OnGUI` into the constructor but instead creating a new label from the `property.displayName` attribute with the `EditorGUIUtility.TrTempContent(label)` method.

This causes the tooltip to be always empty because we are actually creating a completely new `GUIContent` object that does not retain the previously changed information.

---------------------------------------------------------

I only fixed it for the `MinMaxSliderInt` for now to test it. See the adjusted constructor below (The other 2 constructors are not needed anymore, because we don't need to construct a `GUIContent` ourselves from the `property.displayName`.

```csharp
public static void MinMaxSliderInt(Rect position, SerializedProperty property, GUIContent label, int minLimit, int maxLimit, SliderFieldPosition minValueFieldPosition = MinMaxSliderAttribute.DefaultMinFieldPosition, SliderFieldPosition maxValueFieldPosition = MinMaxSliderAttribute.DefaultMaxFieldPosition)
{
        var propertyLabel = EditorGUI.BeginProperty(position, label, property);
        Vector2Int value = property.vector2IntValue;
        EditorGUI.BeginChangeCheck();
        value = MinMaxSliderInt(position, propertyLabel, value, minLimit, maxLimit, minValueFieldPosition, maxValueFieldPosition);
        if (EditorGUI.EndChangeCheck())
        {
            property.vector2IntValue = value;
        }
        EditorGUI.EndProperty();
}
```

New way to call the constructor

```csharp
// Check for Vector2Int
else if (property.propertyType == SerializedPropertyType.Vector2Int)
{
    MMSEditorGUI.MinMaxSliderInt(position, property, label, Mathf.RoundToInt(minMaxAttribute.Min), Mathf.RoundToInt(minMaxAttribute.Max), minMaxAttribute.MinFieldPosition, minMaxAttribute.MaxFieldPosition);
}
```

-----------------------------------------------------------

If you want to I can create a pull request and integrate the changes myself for all types. Would be probably be able to do that this saturday.

**Comment by ayellowpaper** [comment]
Thank you for your thorough investigation of the issue. I have just updated the project with a new version containing a fix.
I have kept all constructors as before, as not everyone wants to bother with GUIContent. But the properties will now properly pass the available GUIContent.

By the way, the new version also supports display of the range in the actual slider. :)

**Comment by MathewHDYT** [comment]
Would be nice if a short documentation section could be added about. Displaying the Range value on the Slider.

```csharp
MMSEditorGUI.ShowRangeValue = true;
```

And the issue has been resolved and works like a charm thanks a lot. Amazing library by the way :D.

![image](https://user-images.githubusercontent.com/48954742/184478028-f9f68f7a-ddb1-415a-8d06-8cefc2469900.png)
